FROM maven:3.9 AS build
WORKDIR /app
COPY document-managmenet/pom.xml .
RUN mvn dependency:go-offline -B
COPY document-management/src ./src
RUN mvn package -DskipTests

FROM gcr.io/distroless/java21
WORKDIR /app
EXPOSE 8080
COPY --from=build /app/target/*.jar app.jar
CMD ["app.jar"]