ACTIVE_PROFILE: ${ACTIVE_PROFILE}
CONTAINER_PORT: 8085

POSTGRESQL_HOST: ${POSTGRESQL_HOST}
POSTGRESQL_PORT: ${POSTGRESQL_PORT}
POSTGRESQL_DB: ${POSTGRESQL_DB}
POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
POSTGRESQL_SSL: ${POSTGRESQL_SSL}

EMAIL_HOST: ${EMAIL_HOST}
EMAIL_PORT: ${EMAIL_PORT}
EMAIL_ID: ${EMAIL_ID}
EMAIL_PASSWORD: ${EMAIL_PASSWORD}
VERIFY_EMAIL_HOST: ${APP_URL}

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}