ACTIVE_PROFILE: dev
CONTAINER_PORT: 8085

POSTGRESQL_HOST: 172.25.160.1
POSTGRESQL_PORT: 5432
POSTGRESQL_DB: "document-managementdb"
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: "@Adoustar4"
POSTGRESQL_SSL: ""

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: adama.daffeh07@gmail.com
EMAIL_PASSWORD: "gntsishiovzankof"
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}